2023-03-02 23:44:45 align.main INFO : Reading netlist: /home/kevin/Downloads/msvsd3bitfadc/week3/align-counter/counter/counter.sp subckt=COUNTER, flat=0
2023-03-02 23:44:45 align.compiler.compiler INFO : Starting topology identification...
2023-03-02 23:44:46 align.compiler.compiler INFO : Power and ground nets not found. Power grid will not be constructed.
2023-03-02 23:44:46 align.compiler.compiler INFO : Completed topology identification.
2023-03-02 23:44:46 align.cell_fabric.remove_duplicates ERROR : Found errors: SHORT: 0 OPEN: 2 DIFFERENT WIDTH: 0
2023-03-02 23:44:46 align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cmdline.py", line 176, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/main.py", line 178, in schematic2layout
    primitives = generate_primitives(primitive_lib, pdk_dir, primitive_dir, netlist_dir)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/primitive/main.py", line 152, in generate_primitives
    uc = generate_primitive(block_name, primitive_def,  ** block_args,
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/primitive/main.py", line 196, in generate_primitive
    uc.writeJSON(fp)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cell_fabric/canvas.py", line 440, in writeJSON
    data = self.gen_data( draw_grid=draw_grid, run_drc=run_drc, run_pex=run_pex, postprocess=postprocess)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cell_fabric/canvas.py", line 415, in gen_data
    'terminals' : self.removeDuplicates(nets_allowed_to_be_open=nets_allowed_to_be_open)}
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cell_fabric/canvas.py", line 406, in removeDuplicates
    return self.rd.remove_duplicates(silence_errors=silence_errors)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cell_fabric/remove_duplicates.py", line 332, in remove_duplicates
    self.check_shorts_induced_by_vias()
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cell_fabric/remove_duplicates.py", line 275, in check_shorts_induced_by_vias
    metal_rect_h = metal_scan_line_horizontal.find_touching(via_rect)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cell_fabric/remove_duplicates.py", line 89, in find_touching
    assert result is not None, (via_rect, self.rects)
AssertionError: (([350, -1360, 550, -1160], 'MINUS', 'drawing'), [([-595, -1660, 165, -860], 'MINUS', 'pin')])
