2023-02-17 17:44:24 align.main INFO : Reading netlist: /home/kevin/Documents/msvsd3bitfadc/week0/align-section7/section7/section7.sp subckt=SECTION7, flat=0
2023-02-17 17:44:24 align.compiler.compiler INFO : Starting topology identification...
2023-02-17 17:44:24 align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/cmdline.py", line 176, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/main.py", line 164, in schematic2layout
    primitive_lib = generate_hierarchy(netlist, subckt, topology_dir, flatten, pdk_dir)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/compiler/compiler.py", line 27, in generate_hierarchy
    ckt_data, primitive_library = compiler_input(
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/compiler/compiler.py", line 76, in compiler_input
    ckt_parser.parse(lines)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/schema/parser.py", line 88, in parse
    self._dispatch(cache)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/schema/parser.py", line 106, in _dispatch
    self._process_instance(token.value.upper(), args, kwargs)
  File "/home/kevin/ALIGN-public/general/lib/python3.10/site-packages/align/schema/parser.py", line 161, in _process_instance
    assert len(args) == len(model.pins), \
AssertionError: Model SKY130_FD_PR__NFET_01V8 has 4 pins ['D', 'G', 'S', 'B']. 16 nets ['A_44_76#', 'C', 'A_28_76#', 'A_28_76#', 'SKY130_FD_PR__PFET_01V8', 'M3', 'A_92_18#', 'D', 'GND', 'GND', 'SKY130_FD_PR__NFET_01V8', 'M4', 'GND', 'F', 'A_60_18#', 'A_60_18#'] were passed when instantiating M2.
